using Microsoft.AspNet.Identity;
using Microsoft.Owin;
using Microsoft.Owin.Security.Cookies;
using Owin;

namespace Treehouse.FitnessFrog
{
	public partial class Startup
	{
		private void ConfigureAuth(IAppBuilder app)
		{
			app.UseCookieAuthentication(new CookieAuthenticationOptions
			{
				AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
				LoginPath = new PathString("/Account/SignIn"),
				Provider = new CookieAuthenticationProvider(),
				CookieSecure = CookieSecureOption.Always, // always issue secure cookies; the authentication cookie that is generated by Identity is signed and encrypted whether the request is made with SSL or not
				CookieHttpOnly = true // instruct the browser to prevent the cookie from being accessible via JavaScript which will help prevent cross-site scripting attacks
			});
		}
	}
}